// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using project.DAL.DataContext;

namespace project.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220216111332_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("project.Entity.Entities.Administrators", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("AdminDOB")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AdminGender")
                        .HasColumnType("text");

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AdminPassword")
                        .HasColumnType("integer");

                    b.Property<string>("AdminSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("UserAge")
                        .HasColumnType("integer");

                    b.Property<string>("UserEmail")
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("project.Entity.Entities.Floor", b =>
                {
                    b.Property<int>("FloorNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.HasKey("FloorNumber");

                    b.ToTable("Floor");
                });

            modelBuilder.Entity("project.Entity.Entities.Guests", b =>
                {
                    b.Property<int>("GuestNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("GuestStayFrom")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("GuestStayTo")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomMax")
                        .HasColumnType("integer");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer");

                    b.HasKey("GuestNumber");

                    b.HasIndex("RoomNumber");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("project.Entity.Entities.Room", b =>
                {
                    b.Property<int>("RoomNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("RoomCost")
                        .HasColumnType("integer");

                    b.Property<int>("RoomMax")
                        .HasColumnType("integer");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RoomPictureFilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoomNumber");

                    b.HasIndex("FloorNumber");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("project.Entity.Entities.Guests", b =>
                {
                    b.HasOne("project.Entity.Entities.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("project.Entity.Entities.Room", b =>
                {
                    b.HasOne("project.Entity.Entities.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("project.Entity.Entities.Floor", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
